services:
  - type: web
    name: cinenext-ml
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ml_server.server:app
    envVars:
      - key: TMDB_API_TOKEN
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
